# Generated by Django 4.2.2 on 2023-06-29 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_city', models.CharField(max_length=50, verbose_name='В')),
                ('hotel_title', models.CharField(max_length=50, verbose_name='Название отеля')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Звезд у отеля')),
                ('image', models.URLField(verbose_name='Ссылка на фото')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('nights', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ночей')),
                ('date', models.DateField(verbose_name='Дата')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city', to_field='name', verbose_name='Из')),
            ],
            options={
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
